### ISSUE TITLE
can't import LonaApp on windows/python38

### ISSUE THREAD

**Issue by simcup** [lona-web-org/lona#202]
hey, i can't import LonaApp from lona after install via pip in python 3.8.5 on windows 10. see attached screenshots. IDLE was opened after installation
![Lona_fail_1](https://user-images.githubusercontent.com/959467/151143168-30cfeba8-883b-4260-a8f7-1a5ebd28f666.png)
![Lona_fail_2](https://user-images.githubusercontent.com/959467/151143288-5aed9705-5c77-4020-88a6-b5f0dadac552.png)
![Lona_fail_3](https://user-images.githubusercontent.com/959467/151143311-85d96919-1282-48e1-9558-64a49bf3a957.png)

**Comment by fscherf** [comment]
Hi @simcup,

Thanks for the detailed bug report! The problem is known and should be fixed in master. I am currently working on a release. I would recommend to use a prior version or the current master. To use the current master run ``pip install git+https://github.com/lona-web-org/lona@master``

I will notify you here when the fixed version is released (should be until friday)

**Comment by laundmo** [comment]
JSYK; i went through and tested previous versions, the most recent one without this bug is 1.8.1

**Comment by simcup** [comment]
works  fine with version 1.9
