### ISSUE TITLE
CLIENT_VERSION 2 adds spurious <div>

### ISSUE THREAD

**Issue by markusgritsch** [lona-web-org/lona#364]
This example
```Python
from lona import LonaApp, LonaView
from lona.html import HTML, TextInput

app = LonaApp(__file__)
app.settings.CLIENT_VERSION = 1

@app.route('/')
class MyView(LonaView):
    def handle_request(self, request):
        return HTML(
            '<br>',
            'f<sub>1</sub>:', '&nbsp;', TextInput(),
        )

app.run(host='0.0.0.0', port=8080)
```
correctly displays
![grafik](https://user-images.githubusercontent.com/2684183/225732886-d899d9be-a526-45e2-9e70-c8ff9e8c494b.png)

When setting `CLIENT_VERSION = 2` the `<sub>` tag causes an additional `<div>` to be inserted, which leads to a not intended line break:
![grafik](https://user-images.githubusercontent.com/2684183/225733243-da64d5f4-710f-4f90-aeec-32d53ec6a800.png)

Sidenote; Without the `<sup>` tag, both `CLIENT_VERSION = 1` and `2` produce the same result:
![grafik](https://user-images.githubusercontent.com/2684183/225733601-543bace3-4a70-4dfb-ba62-e388ed2907b7.png)

**Comment by fscherf** [comment]
@markusgritsch: This is wanted behavior. In Lona 2 (client2 is the client implementation of the planned Lona 2 release), every view has to have exactly one root node. If you parse a string, that would result in multiple root nodes, one `div` gets wrapped around the output.

Client 1 had support for multiple root nodes, but this feature was removed, to simplify the rendering code in the client (https://github.com/lona-web-org/lona/discussions/228 paragraph 1).

Why this specialty?
Since Lona is a SPA framework, `lona.html.HTML` was never supposed to return an actual HTML node with the tag name `html`, but was domain-specific-language to indicate "this view returns HTML in some form (string or nodes)".

In order to make code like this
```python
return HTML(
    H1('Hello World'),
    P('Lorem Ipsum'),
)
```
work, but not to break the only-one-root-node-rule, an extra node has to be inserted.

**Comment by markusgritsch** [comment]
I think I do not completely understand the explanation. The strange thing is that just by adding the <sub> tag causes this. So how to get the output of the first image with Lona 2?

**Comment by fscherf** [comment]
@markusgritsch: I am sorry. What i wanted to say is, that the outer div is wanted, the inner one, wrapping the `f` is not wanted, and seems to be a bug in `lona.html.HTML`.
I pushed a potential fix to `fscherf/topic/client2/fix-html-parsing`.

**Comment by fscherf** [comment]
@markusgritsch: Ok great :) Thanks for reporting. I will cleanup the patch, add a test, and create a PR.
