### ISSUE TITLE
Question: How to upload files?

### ISSUE THREAD

**Issue by SmithChart** [lona-web-org/lona#463]
I've been looking into uploading files to a Lona server. 

Last time I had this problem I solved it using an non-interactive view that handled the actual upload. That was OK for the toy-project at the time (See [View](https://gitli.stratum0.org/chrissi/lona-infobeamer/-/blob/c88e78d5553df7ed1e874d77522a7ed32008405c/lona_project/views/backend.py#L49) and [routing](https://gitli.stratum0.org/chrissi/lona-infobeamer/-/blob/c88e78d5553df7ed1e874d77522a7ed32008405c/lona_project/routes.py#L10) ). But now I want to find a solution that integrates a little nicer into an interactive Lona view.

When using a `<form>` with an `<input type="file">` this fails, since Lona does not send the files content to the server when intercepting (and faking) the POST-request. So this example does not work at the moment:
```
class File(Node):
    TAG_NAME = "input"
    SELF_CLOSING_TAG = True

    ATTRIBUTES = {
        "type": "file",
    }


@app.route("/")
class Index(View):
    def handle_request(self, request):
        if request.method == "POST":
            print(request.POST)

        return HTML(
            H1("Enter your name"),
            Form(
                File(name="file"),
                TextInput(name="name"),
                Submit("Submit"),
                action=".",
                method="post",
            ),
        )
```
This will print (`{'file': {}, 'name': 'abc'}`) when typing "abc" into the text field.

I could try to implement a custom JavaScript based solution for this. But before doing so I wanted to know if anyone already has an Opinion on how we want to go forward here. I guess uploading files is not a very common problem, but still is needed from time to time.

**Comment by fscherf** [comment]
Hi @SmithChart,

That's a feature Lona is missing since the begin of this project. Basically, you can just use aiohttp file upload in an non-interactive, http-pass-through view as you did, but I want to add a more user-friendly feature to the library.

I was working on this: https://github.com/lona-web-org/lona/compare/master...fscherf/topic/file-upload

It is pretty much what you are doing, but using a generic middleware, instead of a view. That way is easier to configure and you don't have to add a custom file upload view to the routing table of every project that wants to use it.

My idea was to provide an python API like this:

```python
from lona_dropzone import DropZone            
                                              
bucket = server.get_file_bucket(              
    max_files=3,                              
    max_size=1024,                            
    list_files=True,                          
)

bucket.list_files() # -> ['/tmp/euhaeu12/file-1.png', ]                                            
                                              
HTML(                                         
    H1('Drag & Drop your files here'),        
    DropZone(                                 
        bucket=bucket,                        
        handle_file_upload=lambda e: print(e),
    ),                                        
)                                             
```
As you mentioned, we will need something that does the actual upload, using a POST request, and I was looking at a project like https://www.dropzone.dev/

btw: The name `bucket` was my first idea, because in my head its like an area where you can dump things and list and remove them afterwards. I am open to better names :D

**Comment by SmithChart** [comment]
This sounds like the API that i want to use :-) Also I like the idea of using a well-tested project. Especially the chunked upload method sounds promising. Especially when planning on uploads for larger files.

`bucket` sounds fine. Stuff like `store` sounds too permanent.

Do you have a plan on cleaning up unused files from the buckets? I initially thought about a context manager. But that would be too limiting when using event handlers.
It would be nice to have a way to tidy up uploaded files once the view (or lona) ends.

**Comment by fscherf** [comment]
Valid point. Then it should be `View.get_file_bucket()` instead of `Server.get_file_bucket()`. Then the buckets are linked to a view, and the server can cleanup all buckets when the view gets removed from the server.

**Comment by SmithChart** [comment]
`view.get_file_bucket()` sounds like the right place for that. Thx!
