### ISSUE TITLE
Integration with brython

### ISSUE THREAD

**Issue by nacho00112** [lona-web-org/lona#474]
It should be very easy to integrate [lona](https://github.com/lona-web-org/lona) with [brython](https://github.com/brython-dev/brython) and with the `brython-cli` command that you will probably need too, it's available once you install [brython via PyPI (pip)](https://pypi.org/project/brython), brython is a python interpreter written in javascript designed to work in the browser, it can do anything that javascript can do, it's highly optimized and therefore fast, support all the python syntax and have almost all the libraries of the standard library, more than enough to create complex widgets using python including animations, it would be two python interpreters, one working in the backend and another in the frontend, it sounds cool it does not?

As i said it should be very easy to integrate with lona you already have the widget interface so you will only need to add the option to load the python files using brython, here is when `brython-cli install` and `brython-cli make_modules` comes in

**Comment by fscherf** [comment]
@nacho00112: I think you should be able to integrate brython with Lona without too many issues.
Look at [chartjs](https://github.com/lona-web-org/lona-chartjs/blob/master/lona_chartjs/html.py#L9) for example. The chart node tells Lona to load the ChartJS JavaScript blob first, and then the Lona widgets that do the adapting.

I didn't use brython yet, but there might be problems because brython expects some attributes on its script tags. That can be solved by just adding a custom [Lona frontend](https://lona-web.org/1.x/api-reference/frontends.html#custom-templates).

**Comment by fscherf** [comment]
Hi @nacho00112! Did you get it working in the meantime? This issue is open for a while now.

**Comment by fscherf** [comment]
@nacho00112 I will close this issue for now. Feel free to reopen it if you have additional questions.
