### ISSUE TITLE
Browser back button not working in Firefox

### ISSUE THREAD

**Issue by m-reichle** [lona-web-org/lona#550]
Hi, 

I'm currently looking into an issue where the browser's back button does not work as expected when accessing Lona views using the Firefox browser. It works as expected when using Chrome/-ium but only seems to create a reload in Firefox.

Has anyone observed the same problem and/or found a way to solve it? I'm mostly puzzled by this only occurring in one browser.

**Comment by fscherf** [comment]
Hi @m-reichle! 
Interesting! Do I have to do something specific to trigger your problem? Do you have a reproducer for me?

**Comment by fscherf** [comment]
Hi @m-reichle. I can reproduce the problem and it is a bug for sure. The history behavior is wrong, but both browsers behave the same for me. I debugged it already, and I think the problem is that I invoke `pushState` too often. So the history is actually "correct", but I add too many entries to it. I hope to have a solution ready this week.

Thanks for reporting! :)

**Comment by fscherf** [comment]
@m-reichle: can you check if #552 fixes your issue?

**Comment by m-reichle** [comment]
Hi, 

I've tested it both with my test case and our in-house application and it seems to have fixed the issue. 
Thank you for taking care of this!

**Comment by fscherf** [comment]
@m-reichle: Great! Thanks for testing :)
No problem.

I will cleanup the PR a bit and merge it afterwards. I assume you need a release right?

**Comment by fscherf** [comment]
@m-reichle: The fix is available in 1.16.2. Thanks for contributing :)

**Comment by m-reichle** [comment]
Awesome! Thanks a lot!!
